### ISSUE TITLE
When I training I have a problem.

### ISSUE THREAD

**Issue by wntg** [OpenGVLab/UniFormerV2#4] opened 2022-11-23 14:31 UTC
-- Process 5 terminated with the following error:
Traceback (most recent call last):
  File "/root/miniconda3/envs/xclip/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/root/workspace/UniFormerV2-main/slowfast/utils/multiprocessing.py", line 60, in run
    ret = func(cfg)
  File "/root/workspace/UniFormerV2-main/tools/train_net.py", line 489, in train
    train_loader, model, optimizer, loss_scaler, train_meter, cur_epoch, cfg, writer
  File "/root/workspace/UniFormerV2-main/tools/train_net.py", line 105, in train_epoch
    loss_scaler(loss, optimizer, clip_grad=cfg.SOLVER.CLIP_GRADIENT, parameters=model.parameters(), create_graph=is_second_order)
  File "/root/miniconda3/envs/xclip/lib/python3.7/site-packages/timm/utils/cuda.py", line 43, in __call__
    self._scaler.scale(loss).backward(create_graph=create_graph)
  File "/root/miniconda3/envs/xclip/lib/python3.7/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/root/miniconda3/envs/xclip/lib/python3.7/site-packages/torch/autograd/__init__.py", line 175, in backward
    allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.HalfTensor [4, 768, 8, 14, 14]], which is output 0 of AsStridedBackward0, is at version 1; expected version 0 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

**Comment by Andy1621** [comment] 2022-11-23 16:40
It might be caused by different versions of PyTorch or CUDA. You can try to add `clone` here:
https://github.com/OpenGVLab/UniFormerV2/blob/6a678d0b82435fd7f86757cedc35de00bb28ced3/slowfast/models/uniformerv2_model.py#L263

Thus line264 is as follows：
```python
tmp_feats = self.dpe[j](tmp_feats.clone()).view(N, C, T_down, L - 1).permute(3, 0, 2, 1)
```

**Comment by Andy1621** [comment] 2022-11-27 09:15
@wntg Hi! Have you solved the problem?

**Comment by Andy1621** [comment] 2022-11-30 14:19
As there is no more activity, I am closing the issue, don't hesitate to reopen it if necessary.

**Closed by Andy1621** 2022-11-30 14:19 UTC
Labels: good first issue

**Comment by xiezexun** [comment] 2023-07-29 11:01
请问，有vit_b16.pth的链接吗？我下载的预训练模型权重参数不匹配

**Comment by Andy1621** [comment] 2023-07-30 14:40
请查看https://github.com/OpenGVLab/UniFormerV2/blob/main/extract_clip/extract.ipynb
